/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recargas;

import javax.swing.JOptionPane;


public class WinRecarga extends javax.swing.JFrame {

   
    public WinRecarga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tiposRecargas = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        entrada = new javax.swing.JTextField();
        totalPines = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        recarga1 = new javax.swing.JRadioButton();
        recarga3 = new javax.swing.JRadioButton();
        recarga5 = new javax.swing.JRadioButton();
        recarga6 = new javax.swing.JRadioButton();
        recarga10 = new javax.swing.JRadioButton();
        btnverificar = new javax.swing.JButton();
        corregir = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 0, 10)); // NOI18N
        jLabel1.setText("PINES DE RECARGA");

        jLabel2.setText("ENTRADA DEL DÍA");

        jLabel3.setText("TOTAL DE PINES");

        entrada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        totalPines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPinesActionPerformed(evt);
            }
        });

        jLabel4.setText("RECARGAS");

        tiposRecargas.add(recarga1);
        recarga1.setText("$1");
        recarga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recarga1ActionPerformed(evt);
            }
        });

        tiposRecargas.add(recarga3);
        recarga3.setText("$3");

        tiposRecargas.add(recarga5);
        recarga5.setText("$5");

        tiposRecargas.add(recarga6);
        recarga6.setText("$6");

        tiposRecargas.add(recarga10);
        recarga10.setText("$10");

        btnverificar.setBackground(new java.awt.Color(51, 204, 0));
        btnverificar.setText("VERIFICAR");
        btnverificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverificarActionPerformed(evt);
            }
        });

        corregir.setBackground(new java.awt.Color(0, 153, 153));
        corregir.setText("CORREGIR");
        corregir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corregirActionPerformed(evt);
            }
        });

        salir.setBackground(new java.awt.Color(255, 0, 0));
        salir.setText("SALIR");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(entrada)
                            .addComponent(totalPines, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recarga1)
                            .addComponent(recarga3)
                            .addComponent(recarga5)
                            .addComponent(recarga6)
                            .addComponent(recarga10))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnverificar)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(salir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(corregir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(totalPines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recarga1)
                    .addComponent(btnverificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recarga3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(recarga5)
                    .addComponent(corregir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(recarga6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recarga10)
                    .addComponent(salir))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void validarboton(){
           
      if (recarga1.isSelected()) {
            String cadena = totalPines.getText();
            String dinero = entrada.getText();
            int uno = Integer.parseInt(cadena);
            int dolares = Integer.parseInt(dinero);
            int rec1 = uno - 1;
            int dine1 = dolares + 1; 
            totalPines.setText(String.valueOf(rec1));
            entrada.setText (String.valueOf(dine1));
            JOptionPane.showMessageDialog(null, "Se realizo recarga de $1" );
            
        }else if (recarga3.isSelected()) {
            String cadena = totalPines.getText();
            String dinero = entrada.getText();
            int uno = Integer.parseInt(cadena);
            int dolares = Integer.parseInt(dinero);
            int rec1 = uno - 3;
            int dine1 = dolares + 3; 
            totalPines.setText(String.valueOf(rec1));
            entrada.setText (String.valueOf(dine1));
            JOptionPane.showMessageDialog(null, "Se realizo recarga de $3");
        }else if (recarga5.isSelected()) {
            String cadena = totalPines.getText();
            String dinero = entrada.getText();
            int uno = Integer.parseInt(cadena);
            int dolares = Integer.parseInt(dinero);
            int rec1 = uno - 5;
            int dine1 = dolares + 5; 
            totalPines.setText(String.valueOf(rec1));
            entrada.setText (String.valueOf(dine1));
            JOptionPane.showMessageDialog(null, "Se realizo recarga de $5");
        }else if (recarga6.isSelected()) {
            String cadena = totalPines.getText();
            String dinero = entrada.getText();
            int uno = Integer.parseInt(cadena);
            int dolares = Integer.parseInt(dinero);
            int rec1 = uno - 6;
            int dine1 = dolares + 6; 
            totalPines.setText(String.valueOf(rec1));
            entrada.setText (String.valueOf(dine1));
            JOptionPane.showMessageDialog(null, "Se realizo recarga de $6");
        }else if (recarga10.isSelected()) {
            String cadena = totalPines.getText();
            String dinero = entrada.getText();
            int uno = Integer.parseInt(cadena);
            int dolares = Integer.parseInt(dinero);
            int rec1 = uno - 10;
            int dine1 = dolares + 10; 
            totalPines.setText(String.valueOf(rec1));
            entrada.setText (String.valueOf(dine1));
            JOptionPane.showMessageDialog(null, "Se realizo recarga de $10");
             
        }
       
    }
    
     
    private void btnverificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverificarActionPerformed
        // CONTROLA QUE NO HAGA MAS RECARGAS CUANDO EL JTEXTFIELD TIENE UN VALOR DE CERO
        if (totalPines.getText().equals("0")){
            JOptionPane.showMessageDialog(null, "NO HAY PINES, POR FAVOR RECARGAR");
        }else{
        validarboton();}  
              
    }//GEN-LAST:event_btnverificarActionPerformed

    private void totalPinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPinesActionPerformed
                                       
    }//GEN-LAST:event_totalPinesActionPerformed

    private void recarga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recarga1ActionPerformed
        
        
    }//GEN-LAST:event_recarga1ActionPerformed

    private void corregirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corregirActionPerformed
        
        if (recarga1.isSelected()) {
            String cadena = totalPines.getText();
            String dinero = entrada.getText();
            int uno = Integer.parseInt(cadena);
            int dolares = Integer.parseInt(dinero);
            int rec1 = uno + 1;
            int dine1 = dolares - 1; 
            totalPines.setText(String.valueOf(rec1));
            entrada.setText (String.valueOf(dine1));
            JOptionPane.showMessageDialog(null, "REALIZO CORRECCION CON EXITO $1" );
            
        }else if (recarga3.isSelected()) {
            String cadena = totalPines.getText();
            String dinero = entrada.getText();
            int uno = Integer.parseInt(cadena);
            int dolares = Integer.parseInt(dinero);
            int rec1 = uno + 3;
            int dine1 = dolares - 3; 
            totalPines.setText(String.valueOf(rec1));
            entrada.setText (String.valueOf(dine1));
            JOptionPane.showMessageDialog(null, "REALIZO CORRECCION CON EXITO $3");
        }else if (recarga5.isSelected()) {
            String cadena = totalPines.getText();
            String dinero = entrada.getText();
            int uno = Integer.parseInt(cadena);
            int dolares = Integer.parseInt(dinero);
            int rec1 = uno + 5;
            int dine1 = dolares - 5; 
            totalPines.setText(String.valueOf(rec1));
            entrada.setText (String.valueOf(dine1));
            JOptionPane.showMessageDialog(null, "REALIZO CORRECCION CON EXITO $5");
        }else if (recarga6.isSelected()) {
            String cadena = totalPines.getText();
            String dinero = entrada.getText();
            int uno = Integer.parseInt(cadena); // CONVIERTE EL STRING A INT
            int dolares = Integer.parseInt(dinero);
            int rec1 = uno + 6;
            int dine1 = dolares - 6; 
            totalPines.setText(String.valueOf(rec1));
            entrada.setText (String.valueOf(dine1));
            JOptionPane.showMessageDialog(null, "REALIZO CORRECCION CON EXITO $6");
        }else if (recarga10.isSelected()) {
            String cadena = totalPines.getText();
            String dinero = entrada.getText();
            int uno = Integer.parseInt(cadena);
            int dolares = Integer.parseInt(dinero);
            int rec1 = uno + 10;
            int dine1 = dolares - 10; 
            totalPines.setText(String.valueOf(rec1));
            entrada.setText (String.valueOf(dine1));
            JOptionPane.showMessageDialog(null, "REALIZO CORRECCION CON EXITO $10");
        }
        
        
        
    }//GEN-LAST:event_corregirActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        dispose();
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinRecarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinRecarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinRecarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinRecarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinRecarga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnverificar;
    private javax.swing.JButton corregir;
    private javax.swing.JTextField entrada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton recarga1;
    private javax.swing.JRadioButton recarga10;
    private javax.swing.JRadioButton recarga3;
    private javax.swing.JRadioButton recarga5;
    private javax.swing.JRadioButton recarga6;
    private javax.swing.JButton salir;
    private javax.swing.ButtonGroup tiposRecargas;
    private javax.swing.JTextField totalPines;
    // End of variables declaration//GEN-END:variables
}
